name: CI

on:
  push:
    branches: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout appland
        uses: actions/checkout@v6
        with:
          path: appland

      #- name: Copy sample data into project root
        #run: cp -a appland/samples/* .

      - name: Build with Astro
        uses: withastro/action@v6
        with:
          path: appland


